main: net.jahcraft.jahskills.main.Main
name: JahSkills
version: 1.0.0
author: Jamboxman5
api-version: 1.19
depend: [Vault]
softdepend: [PlaceholderAPI]
commands:
  Afflict:
  SkillDB:
  Skillquery:
  Skills:
  Claimmainskill:
  