package net.jahcraft.jahskills.perks;

public enum Perk {
	
	THEGRINDR, HITMAN, BLUNTFORCETRAUMA, 
	THEPUMMELER, SELFDEFENSE, SPOILSOFWAR, 
	SERRATIONS, KILLINGBLOW, BLOODMONEY, 
	
	MOTHERLODE, OREWHISPERER, CAVEVISION,
	CLIMBINGGEAR, THERMALINSULATION, EFFICIENTDIGGER,
	DIVININGROD, SUPERIORSMELTING, MANICMINING,
	
	TREECAPITATOR, LUMBERJACK, MUSHROOMMAN,
	MEGAEXCAVATOR, BIGGERSHOVEL, NATURESTOUCH,
	ISPEAKFORTHETREES, HIPPYHEALING, MANVSWILD,
	
	SLAUGHTERHOUSE, SWEETMEATS, PIGWHISPERER,
	CHRISKYLE, EXPLOSIVESHOTS, INCENDIARYROUNDS,
	BAREHANDEDARCHERY, BOMBTHROWER, SNIPERSENSE,
	
	GREENTHUMB, REPLANTER, FREAKISHFARMING,
	FARMINGFRENZY, FERTILITYTREATMENT, THEBIRDSANDTHEBEES,
	FERTILIZATION, AGRICULTURALSTUDIES, HARSHPARENTING,
	
	XPREBATES, FAMILYRECIPES, THEYFLYNOW,
	SALVAGEOPERATION, QUICKLEARNER, BETTERMENDER,
	ENDERINFUSION, USETHEFORCE, INDUSTRIALREVOLUTION,
	
	LUCKYLOOTER, SWIFTSTEPS, ARTOFTHEDEAL,
	HIGHDEMAND, KENTUCKYDERBY, CALLOFTHEWILD,
	NEPTUNEFLIGHT, TREASURESNIFFER, NAVIGATIONALSKILLS,
	
	YOUMISSEDME, ARTFULDODGER, RESURRECTION,
	ATTACKOFTHECLONES, GORDONRAMSAY, EMTCERTIFIED,
	SUPERFOODS, UNMATCHEDWILLPOWER, SUPERSAIYAN
	
	

}
