package net.jahcraft.jahskills.perks;

public enum Perk {
	
	THEGRINDR, HITMAN, BLUNTFORCETRAUMA, 
	THEPUMMELER, SELFDEFENSE, SPOILSOFWAR, 
	SERRATIONS, KILLINGBLOW, BLOODMONEY, 
	
	MOTHERLODE, OREWHISPERER, CAVEVISION,
	CLIMBINGGEAR, THERMALINSULATION, EFFICIENTDIGGER,
	DIVININGROD, WEEPINGCREEPERS, MANICMINING
	

}
